// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using proj_back.Models;

namespace proj_back.Data
{
    public partial class GradprojdataContext : DbContext
    {
        public GradprojdataContext()
        {
        }

        public GradprojdataContext(DbContextOptions<GradprojdataContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CharityEventsTable> CharityEventsTables { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CharityEventsTable>(entity =>
            {
                entity.HasKey(e => e.EventId);

                entity.ToTable("charity_events_table");

                entity.Property(e => e.EventId).HasColumnName("event_id");

                entity.Property(e => e.EventDate)
                    .HasColumnType("datetime")
                    .HasColumnName("event_date");

                entity.Property(e => e.EventDescription)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("event_description");

                entity.Property(e => e.EventLocation)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("event_location");

                entity.Property(e => e.EventName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("event_name");

                entity.Property(e => e.EventTime)
                    .IsRequired()
                    .HasMaxLength(5)
                    .HasColumnName("event_time")
                    .IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}