// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace proj_back.Models
{
    public partial class Story
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string story { get; set; }
        public string Title { get; set; }
    }
}